import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Direct port from design/code.html (Material 3 obsidian palette)
        "secondary-fixed": "#d4e4fa",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#a7b6cc",
        "surface-dim": "#111316",
        "surface-variant": "#333538",
        "primary-container": "#dde3eb",
        "tertiary-fixed-dim": "#b9c7e0",
        "surface-bright": "#37393d",
        "tertiary": "#ffffff",
        "inverse-primary": "#595f66",
        "surface-container": "#1e2023",
        "surface": "#111316",
        "secondary": "#b9c8de",
        "on-secondary-fixed": "#0d1c2d",
        "primary-fixed-dim": "#c1c7cf",
        "outline-variant": "#44474a",
        "tertiary-fixed": "#d5e3fd",
        "on-tertiary-fixed": "#0d1c2f",
        "on-primary-fixed-variant": "#41474e",
        "on-error": "#690005",
        "surface-container-lowest": "#0c0e11",
        "inverse-on-surface": "#2f3034",
        "surface-container-low": "#1a1c1f",
        "inverse-surface": "#e2e2e6",
        "outline": "#8e9195",
        "error": "#ffb4ab",
        "tertiary-container": "#d5e3fd",
        "error-container": "#93000a",
        "background": "#000000",
        "on-surface-variant": "#c5c6cb",
        "primary-fixed": "#dde3eb",
        "on-tertiary": "#233144",
        "surface-container-high": "#282a2d",
        "on-secondary": "#233143",
        "on-surface": "#ffffff",
        "secondary-fixed-dim": "#b9c8de",
        "secondary-container": "#39485a",
        "on-tertiary-container": "#57657b",
        "on-tertiary-fixed-variant": "#3a485c",
        "on-secondary-fixed-variant": "#39485a",
        "on-primary-fixed": "#161c22",
        "primary": "#ffffff",
        "on-primary-container": "#5f656c",
        "on-primary": "#2b3137",
        "surface-tint": "#c1c7cf",
        "surface-container-highest": "#333538",
        "on-background": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "container-max": "1200px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        sans: ["Geist", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.03em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
      keyframes: {
        "fade-in": { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.4s ease-out",
        "fade-up": "fade-up 0.5s ease-out",
        shimmer: "shimmer 2s linear infinite",
      },
    },
  },
  plugins: [],
};

export default config;
